"""empty message

Revision ID: 6d74e290c99a
Revises: ac42e07be307
Create Date: 2023-06-10 14:04:37.090497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d74e290c99a'
down_revision = 'ac42e07be307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint('account_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('transaction_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accounts', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('accounts')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_foreign_key('transaction_ibfk_1', 'account', ['account'], ['id'])

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_foreign_key('account_ibfk_1', 'user', ['client_id'], ['id'])

    # ### end Alembic commands ###
