"""empty message

Revision ID: 749b22023c91
Revises: 7f665723ef23
Create Date: 2023-06-10 23:13:48.316994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749b22023c91'
down_revision = '7f665723ef23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sum', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('sum')

    # ### end Alembic commands ###
