"""empty message

Revision ID: df9a4e4ee216
Revises: 6d74e290c99a
Create Date: 2023-06-10 14:38:53.269808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df9a4e4ee216'
down_revision = '6d74e290c99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=False))
        batch_op.alter_column('client_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
